---
matrix:
  include:
    - language: python
      python: 2.7
      script: make pyunit
    - language: bash
      before_script: "sudo curl -o /usr/local/bin/shunit2 https://raw.githubusercontent.com/kward/shunit2/master/shunit2"
      script: make shunit2
notifications:
  email: false
